// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcProcessesStorageSyncImageParamsModule from './imageParams';
import * as srcProcessesStorageSyncProviderProbeCacheModule from './providerProbeCache';
import * as srcProcessesStorageSyncRequestPresetsModule from './requestPresets';
import * as srcProcessesStorageSyncStudioSettingsModule from './studioSettings';
import type { SyncDocumentDescriptor } from './documentSyncEngine';

export const storageSyncDescriptorFallbackModules: Record<string, Record<string, unknown>> = {
  './imageParams.ts': srcProcessesStorageSyncImageParamsModule,
  './providerProbeCache.ts': srcProcessesStorageSyncProviderProbeCacheModule,
  './requestPresets.ts': srcProcessesStorageSyncRequestPresetsModule,
  './studioSettings.ts': srcProcessesStorageSyncStudioSettingsModule
};
