// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcDomainGenerationStatusesCancelledStatusModule from './generation-statuses/cancelled.status';
import * as srcDomainGenerationStatusesCreatedStatusModule from './generation-statuses/created.status';
import * as srcDomainGenerationStatusesDeletedStatusModule from './generation-statuses/deleted.status';
import * as srcDomainGenerationStatusesFailedStatusModule from './generation-statuses/failed.status';
import * as srcDomainGenerationStatusesQueuedStatusModule from './generation-statuses/queued.status';
import * as srcDomainGenerationStatusesRetryingStatusModule from './generation-statuses/retrying.status';
import * as srcDomainGenerationStatusesRunningStatusModule from './generation-statuses/running.status';
import * as srcDomainGenerationStatusesSendingStatusModule from './generation-statuses/sending.status';
import * as srcDomainGenerationStatusesSucceededStatusModule from './generation-statuses/succeeded.status';
import type { GenerationStatusDescriptor } from './generationStatusTypes';

export const generationStatusFallbackModules: Record<string, Record<string, unknown>> = {
  './generation-statuses/cancelled.status.ts': srcDomainGenerationStatusesCancelledStatusModule,
  './generation-statuses/created.status.ts': srcDomainGenerationStatusesCreatedStatusModule,
  './generation-statuses/deleted.status.ts': srcDomainGenerationStatusesDeletedStatusModule,
  './generation-statuses/failed.status.ts': srcDomainGenerationStatusesFailedStatusModule,
  './generation-statuses/queued.status.ts': srcDomainGenerationStatusesQueuedStatusModule,
  './generation-statuses/retrying.status.ts': srcDomainGenerationStatusesRetryingStatusModule,
  './generation-statuses/running.status.ts': srcDomainGenerationStatusesRunningStatusModule,
  './generation-statuses/sending.status.ts': srcDomainGenerationStatusesSendingStatusModule,
  './generation-statuses/succeeded.status.ts': srcDomainGenerationStatusesSucceededStatusModule
};
