// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcProcessesBatchRunnerHandlersBuiltInBatchTaskHandlersModule from './handlers/builtInBatchTaskHandlers';
import type { BatchTaskReducerHandler } from './batchTaskReducerTypes';

export const batchTaskReducerHandlerFallbackModules: Record<string, Record<string, unknown>> = {
  './handlers/builtInBatchTaskHandlers.ts': srcProcessesBatchRunnerHandlersBuiltInBatchTaskHandlersModule
};
