// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcFeaturesDetailSectionsSnapshotTabsFilesTabModule from './tabs/files.tab';
import * as srcFeaturesDetailSectionsSnapshotTabsParamsTabModule from './tabs/params.tab';
import * as srcFeaturesDetailSectionsSnapshotTabsPromptTabModule from './tabs/prompt.tab';
import * as srcFeaturesDetailSectionsSnapshotTabsTechnicalTabModule from './tabs/technical.tab';
import type { DetailInspectorTabDescriptor } from './detailInspectorTabTypes';

export const detailInspectorTabFallbackModules: Record<string, Record<string, unknown>> = {
  './tabs/files.tab.ts': srcFeaturesDetailSectionsSnapshotTabsFilesTabModule,
  './tabs/params.tab.ts': srcFeaturesDetailSectionsSnapshotTabsParamsTabModule,
  './tabs/prompt.tab.ts': srcFeaturesDetailSectionsSnapshotTabsPromptTabModule,
  './tabs/technical.tab.ts': srcFeaturesDetailSectionsSnapshotTabsTechnicalTabModule
};
