// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import { locale as enLocale } from './locales/en/locale';
import enapp from './locales/en/app.json';
import enattachment from './locales/en/attachment.json';
import enbatch from './locales/en/batch.json';
import encomposer from './locales/en/composer.json';
import endetail from './locales/en/detail.json';
import engallery from './locales/en/gallery.json';
import eninfo from './locales/en/info.json';
import ennav from './locales/en/nav.json';
import enparams from './locales/en/params.json';
import enrequestPresets from './locales/en/requestPresets.json';
import enrequestPreview from './locales/en/requestPreview.json';
import ensettings from './locales/en/settings.json';
import enstatus from './locales/en/status.json';
import { locale as ruLocale } from './locales/ru/locale';
import ruapp from './locales/ru/app.json';
import ruattachment from './locales/ru/attachment.json';
import rubatch from './locales/ru/batch.json';
import rucomposer from './locales/ru/composer.json';
import rudetail from './locales/ru/detail.json';
import rugallery from './locales/ru/gallery.json';
import ruinfo from './locales/ru/info.json';
import runav from './locales/ru/nav.json';
import ruparams from './locales/ru/params.json';
import rurequestPresets from './locales/ru/requestPresets.json';
import rurequestPreview from './locales/ru/requestPreview.json';
import rusettings from './locales/ru/settings.json';
import rustatus from './locales/ru/status.json';
import type { Dictionary, LocaleDictionaryModule } from './types';

function mergeDictionary(...parts: Dictionary[]): Dictionary {
  return Object.assign({}, ...parts);
}

export const localeFallbackModules: Record<string, LocaleDictionaryModule> = {
  './locales/en/index.ts': {
    locale: enLocale,
    dictionary: mergeDictionary(enapp, enattachment, enbatch, encomposer, endetail, engallery, eninfo, ennav, enparams, enrequestPresets, enrequestPreview, ensettings, enstatus)
  },
  './locales/ru/index.ts': {
    locale: ruLocale,
    dictionary: mergeDictionary(ruapp, ruattachment, rubatch, rucomposer, rudetail, rugallery, ruinfo, runav, ruparams, rurequestPresets, rurequestPreview, rusettings, rustatus)
  }
};
