// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcFeaturesDetailModelDescriptorsComfyUiDetailDescriptorModule from './descriptors/comfyUiDetailDescriptor';
import * as srcFeaturesDetailModelDescriptorsRequestSnapshotDetailDescriptorModule from './descriptors/requestSnapshotDetailDescriptor';
import type { ProviderDetailDescriptor } from './detailDescriptorTypes';

export const providerDetailDescriptorFallbackModules: Record<string, Record<string, unknown>> = {
  './descriptors/comfyUiDetailDescriptor.ts': srcFeaturesDetailModelDescriptorsComfyUiDetailDescriptorModule,
  './descriptors/requestSnapshotDetailDescriptor.ts': srcFeaturesDetailModelDescriptorsRequestSnapshotDetailDescriptorModule
};
