// This file is generated by the backend route registry workflow.
// Route groups are composed from descriptors so app startup does not import every route directly.
import { registerAppDocumentStorageRoutes } from './appDocumentStorageRoutes';
import { registerDefaultRoutes } from './defaultRoutes';
import { registerGenerationRoutes } from './generationRoutes';
import { registerGenerationTaskStorageRoutes } from './generationTaskStorageRoutes';
import { registerIntegrationContributedRoutes } from './integrationContributedRoutes';
import { registerIntegrationRoutes } from './integrationRoutes';
import { registerProviderRoutes } from './providerRoutes';
import type { BackendRouteGroup } from './types';

export const backendRouteGroupGeneratedModules: Record<string, BackendRouteGroup> = {
  generation: {
    id: 'generation',
    register: (app, context) => registerGenerationRoutes(app, context.upload, context.generationTasks)
  },
  providers: {
    id: 'providers',
    register: (app) => registerProviderRoutes(app)
  },
  'generation-task-storage': {
    id: 'generation-task-storage',
    register: (app, context) => registerGenerationTaskStorageRoutes(app, context.generationTasks, context.galleryCatalog)
  },
  'app-documents': {
    id: 'app-documents',
    register: (app) => registerAppDocumentStorageRoutes(app)
  },
  integrations: {
    id: 'integrations',
    register: (app, context) => registerIntegrationRoutes(app, context.integrations)
  },
  'integration-contributed-routes': {
    id: 'integration-contributed-routes',
    register: (app, context) => registerIntegrationContributedRoutes(app, context.integrations)
  },
  defaults: {
    id: 'defaults',
    register: (app) => registerDefaultRoutes(app)
  }
};
