// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersBooleanFieldRendererModule from './field-renderers/boolean.fieldRenderer';
import * as srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersJsonFieldRendererModule from './field-renderers/json.fieldRenderer';
import * as srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersNumberFieldRendererModule from './field-renderers/number.fieldRenderer';
import * as srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersSecretFieldRendererModule from './field-renderers/secret.fieldRenderer';
import * as srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersTextFieldRendererModule from './field-renderers/text.fieldRenderer';
import type { ProviderSettingsFieldRendererDescriptor } from './providerSettingsFieldRendererTypes';

export const providerSettingsFieldRendererFallbackModules: Record<string, Record<string, unknown>> = {
  './field-renderers/boolean.fieldRenderer.tsx': srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersBooleanFieldRendererModule,
  './field-renderers/json.fieldRenderer.tsx': srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersJsonFieldRendererModule,
  './field-renderers/number.fieldRenderer.tsx': srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersNumberFieldRendererModule,
  './field-renderers/secret.fieldRenderer.tsx': srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersSecretFieldRendererModule,
  './field-renderers/text.fieldRenderer.tsx': srcFeaturesSettingsSectionsGenerationApiProviderEditorFieldRenderersTextFieldRendererModule
};
