import { useMemo } from 'react';
import { normalizeSelectedModel } from '../../entities/studio-settings';
import { createAppCommands } from '../commands/appCommands';
import type { TranslateFn } from '../commands/types';
import type { WorkspaceDerivedState, WorkspaceState } from './types';

export function useWorkspaceCommands(state: WorkspaceState, derived: WorkspaceDerivedState, t: TranslateFn) {
  return useMemo(() => createAppCommands({
    t,
    mode: derived.mode,
    providerModeId: state.providerModeId,
    providerMode: derived.providerMode,
    providerModes: derived.providerModes,
    params: state.params,
    provider: derived.provider,
    activeProvider: derived.activeProvider,
    activeModel: derived.activeModel,
    payload: derived.payload,
    warnings: derived.warnings,
    targetImage: state.targetImage,
    referenceImages: state.referenceImages,
    mask: state.mask,
    canSubmit: derived.canSubmit,
    batchCanSubmit: derived.batchCanSubmit,
    batchDrafts: state.batchDrafts,
    batchIntervalSeconds: state.batchIntervalSeconds,
    requestPresets: state.requestPresets,
    activeBatchDraft: derived.activeBatchDraft,
    studioSettings: state.studioSettings,
    capabilityReport: state.capabilityReport,
    selectedTaskId: state.selectedTaskId,
    activeGalleryPath: state.activeGalleryPath,
    galleryFolders: state.galleryFolders,
    galleryPins: state.galleryPins,
    galleryTagRecords: state.galleryTagRecords,
    taskHistory: state.taskHistory,
    providerProbeState: {
      setCapabilityReport: state.setCapabilityReport,
      setProbeError: state.setProbeError,
      setProbingProviderId: state.setProbingProviderId,
      setQuickCheckingProviderId: state.setQuickCheckingProviderId,
      setQuickCheckResults: state.setQuickCheckResults
    },
    setProviderModeId: state.setProviderModeId,
    setCompatibilityNotice: state.setCompatibilityNotice,
    setParams: state.setParams,
    setStudioSettings: state.setStudioSettings,
    setParametersOpen: state.setParametersOpen,
    setWorkspaceTab: state.setWorkspaceTab,
    setSidebarCollapsed: state.setSidebarCollapsed,
    setTargetImage: state.setTargetImage,
    setReferenceImages: state.setReferenceImages,
    setMask: state.setMask,
    setSelectedTaskId: state.setSelectedTaskId,
    setSelectedImageId: state.setSelectedImageId,
    setActiveGalleryPath: state.setActiveGalleryPath,
    createGalleryFolder: state.createGalleryFolder,
    deleteGalleryFolder: state.deleteGalleryFolder,
    moveGalleryItem: state.moveGalleryItem,
    pasteGalleryItems: state.pasteGalleryItems,
    setGalleryItemPinned: state.setGalleryItemPinned,
    setGalleryItemTags: state.setGalleryItemTags,
    setBusy: state.setBusy,
    setServerSubmission: state.setServerSubmission,
    setBatchComposerOpen: state.setBatchComposerOpen,
    setBatchDrafts: state.setBatchDrafts,
    setBatchIntervalSeconds: state.setBatchIntervalSeconds,
    setRequestPresets: state.setRequestPresets,
    setBatchParametersDraftId: state.setBatchParametersDraftId,
    normalizeSettings: normalizeSelectedModel
  }), [state, derived, t]);
}
