import type { SettingsCommands } from '../../interface/context/commands';
import type { Locale } from '../../i18n';
import type { SettingsSectionContext, SettingsSectionContextInput } from './settingsTypes';

export function createSettingsSectionContext({
  activeTab,
  locale,
  setLocale,
  activeInfo,
  setActiveInfo,
  activeTheme,
  selectTheme,
  draft,
  generationApi,
  probingProviderId,
  quickCheckingProviderId,
  probeError,
  commands
}: SettingsSectionContextInput & { locale: Locale; setLocale: (locale: Locale) => void; commands: SettingsCommands }): Omit<SettingsSectionContext, 'variant'> {
  return {
    activeTab,
    locale,
    setLocale,
    activeInfo,
    setActiveInfo,
    activeTheme,
    selectTheme,
    draft,
    apiFocus: generationApi.apiFocus,
    setApiFocus: generationApi.setApiFocus,
    selectedProvider: generationApi.selectedProvider,
    selectedModel: generationApi.selectedModel,
    selectedProviderId: generationApi.selectedProviderId,
    selectedModelId: generationApi.selectedModelId,
    setSelectedProviderId: generationApi.setSelectedProviderId,
    setSelectedModelId: generationApi.setSelectedModelId,
    modelsForSelectedProvider: generationApi.modelsForSelectedProvider,
    providerOptions: generationApi.providerOptions,
    probeModel: generationApi.probeModel,
    quickResult: generationApi.quickResult,
    showReport: generationApi.showReport,
    probingProviderId,
    quickCheckingProviderId,
    probeError,
    addProvider: generationApi.addProvider,
    removeProvider: generationApi.removeProvider,
    addModel: generationApi.addModel,
    removeModel: generationApi.removeModel,
    selectModel: generationApi.selectModel,
    patchProvider: generationApi.patchProvider,
    patchModel: generationApi.patchModel,
    firstModelForProvider: generationApi.firstModelForProvider,
    comfyUiData: generationApi.comfyUiData,
    comfyUiProviders: generationApi.comfyUiProviders,
    selectedComfyUiProviderId: generationApi.selectedComfyUiProviderId,
    selectedComfyUiProvider: generationApi.selectedComfyUiProvider,
    setSelectedComfyUiProviderId: generationApi.setSelectedComfyUiProviderId,
    comfyUiCheckpointCache: generationApi.comfyUiCheckpointCache,
    comfyUiLoraCache: generationApi.comfyUiLoraCache,
    comfyUiSamplerCache: generationApi.comfyUiSamplerCache,
    comfyUiSchedulerCache: generationApi.comfyUiSchedulerCache,
    comfyUiUpscaleModelCache: generationApi.comfyUiUpscaleModelCache,
    comfyUiResourcesLoading: generationApi.comfyUiResourcesLoading,
    comfyUiResourcesError: generationApi.comfyUiResourcesError,
    refreshComfyUiResources: generationApi.refreshComfyUiResources,
    addComfyUiProvider: generationApi.addComfyUiProvider,
    addComfyUiLora: generationApi.addComfyUiLora,
    removeComfyUiLora: generationApi.removeComfyUiLora,
    patchComfyUiLora: generationApi.patchComfyUiLora,
    commands
  };
}
