// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcSharedFeaturesDescriptorsApiAutomationFeatureModule from './descriptors/apiAutomation.feature';
import * as srcSharedFeaturesDescriptorsEncryptedStorageFeatureModule from './descriptors/encryptedStorage.feature';
import * as srcSharedFeaturesDescriptorsGalleryClearFeatureModule from './descriptors/galleryClear.feature';
import * as srcSharedFeaturesDescriptorsGalleryDeleteFeatureModule from './descriptors/galleryDelete.feature';
import * as srcSharedFeaturesDescriptorsProviderProbingFeatureModule from './descriptors/providerProbing.feature';
import * as srcSharedFeaturesDescriptorsSettingsFeatureModule from './descriptors/settings.feature';
import * as srcSharedFeaturesDescriptorsStudioInfoFeatureModule from './descriptors/studioInfo.feature';
import type { AppFeatureDescriptor } from './types';

export const featureDescriptorFallbackModules: Record<string, Record<string, unknown>> = {
  './descriptors/apiAutomation.feature.ts': srcSharedFeaturesDescriptorsApiAutomationFeatureModule,
  './descriptors/encryptedStorage.feature.ts': srcSharedFeaturesDescriptorsEncryptedStorageFeatureModule,
  './descriptors/galleryClear.feature.ts': srcSharedFeaturesDescriptorsGalleryClearFeatureModule,
  './descriptors/galleryDelete.feature.ts': srcSharedFeaturesDescriptorsGalleryDeleteFeatureModule,
  './descriptors/providerProbing.feature.ts': srcSharedFeaturesDescriptorsProviderProbingFeatureModule,
  './descriptors/settings.feature.ts': srcSharedFeaturesDescriptorsSettingsFeatureModule,
  './descriptors/studioInfo.feature.ts': srcSharedFeaturesDescriptorsStudioInfoFeatureModule
};
