// This file is generated by scripts/generate-provider-registry.mjs.
// Keep provider manifests in src/providers/*/manifest.ts; regenerate when adding/removing adapters.
import { comfyUiProviderClientManifest } from '../../providers/comfyui/manifest';
import { openAiCompatibleProviderClientManifest } from '../../providers/openai-compatible/manifest';
import type { ProviderClientManifest } from './manifest';

export const providerClientManifestGeneratedModules: Record<string, Record<string, ProviderClientManifest>> = {
  '../../providers/comfyui/manifest.ts': { comfyUiProviderClientManifest },
  '../../providers/openai-compatible/manifest.ts': { openAiCompatibleProviderClientManifest }
};
