// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcEntitiesGenerationParamsComfyuiExtensionsPluginsFreeuV2PluginModule from './freeuV2.plugin';
import * as srcEntitiesGenerationParamsComfyuiExtensionsPluginsLoraStackPluginModule from './loraStack.plugin';
import * as srcEntitiesGenerationParamsComfyuiExtensionsPluginsPagPluginModule from './pag.plugin';
import * as srcEntitiesGenerationParamsComfyuiExtensionsPluginsPerpGuiderPluginModule from './perpGuider.plugin';
import * as srcEntitiesGenerationParamsComfyuiExtensionsPluginsTiledGenerationPluginModule from './tiledGeneration.plugin';
import * as srcEntitiesGenerationParamsComfyuiExtensionsPluginsTiledVaePluginModule from './tiledVae.plugin';
import type { WorkflowPluginDefinition } from '../workflowPluginTypes';

export const workflowPluginGeneratedModules: Record<string, Record<string, unknown>> = {
  './freeuV2.plugin.ts': srcEntitiesGenerationParamsComfyuiExtensionsPluginsFreeuV2PluginModule,
  './loraStack.plugin.ts': srcEntitiesGenerationParamsComfyuiExtensionsPluginsLoraStackPluginModule,
  './pag.plugin.ts': srcEntitiesGenerationParamsComfyuiExtensionsPluginsPagPluginModule,
  './perpGuider.plugin.ts': srcEntitiesGenerationParamsComfyuiExtensionsPluginsPerpGuiderPluginModule,
  './tiledGeneration.plugin.ts': srcEntitiesGenerationParamsComfyuiExtensionsPluginsTiledGenerationPluginModule,
  './tiledVae.plugin.ts': srcEntitiesGenerationParamsComfyuiExtensionsPluginsTiledVaePluginModule
};
