// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcFeaturesSettingsSectionsGenerationApiSectionDescriptorModule from './generation-api/sectionDescriptor';
import * as srcFeaturesSettingsSectionsIntegrationsSectionDescriptorModule from './integrations/sectionDescriptor';
import * as srcFeaturesSettingsSectionsInterfaceSectionDescriptorModule from './interface/sectionDescriptor';
import type { SettingsSectionDescriptor } from './sectionDescriptorTypes';

export const settingsSectionDescriptorFallbackModules: Record<string, Record<string, unknown>> = {
  './generation-api/sectionDescriptor.ts': srcFeaturesSettingsSectionsGenerationApiSectionDescriptorModule,
  './integrations/sectionDescriptor.ts': srcFeaturesSettingsSectionsIntegrationsSectionDescriptorModule,
  './interface/sectionDescriptor.ts': srcFeaturesSettingsSectionsInterfaceSectionDescriptorModule
};
