// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcIntegrationsTelegramDefinitionModule from '../../integrations/telegram/definition';
import type { IntegrationDefinition } from './types';

export const integrationDefinitionFallbackModules: Record<string, Record<string, unknown>> = {
  '../../integrations/telegram/definition.ts': srcIntegrationsTelegramDefinitionModule
};
