// This file is generated by scripts/generate-storage-migration-registry.mjs.
// Keep storage migrations in server/storage/migrations/NNN_*.ts; regenerate when adding/removing migrations.
import { encryptedBlobsMigration } from './001_encrypted_blobs';
import { storageV2DocumentsMigration } from './002_storage_v2_documents';
import { galleryPathsMigration } from './003_gallery_paths';
import type { StorageMigrationDescriptor } from './types';

export const storageMigrationGeneratedModules: Record<string, Record<string, StorageMigrationDescriptor>> = {
  './001_encrypted_blobs.ts': { encryptedBlobsMigration },
  './002_storage_v2_documents.ts': { storageV2DocumentsMigration },
  './003_gallery_paths.ts': { galleryPathsMigration }
};
