// This file is generated by scripts/generate-provider-registry.mjs.
// Keep provider manifests in server/providers/*/manifest.ts; regenerate when adding/removing adapters.
import { comfyUiProviderServerManifest } from './comfyui/manifest';
import { openAiCompatibleProviderServerManifest } from './openai-compatible/manifest';
import type { ProviderServerManifest } from './manifest';

export const providerServerManifestGeneratedModules: Record<string, Record<string, ProviderServerManifest>> = {
  './comfyui/manifest.ts': { comfyUiProviderServerManifest },
  './openai-compatible/manifest.ts': { openAiCompatibleProviderServerManifest }
};
