// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcFeaturesSettingsSectionsIntegrationsTelegramPanelModule from './telegram.panel';
import type { IntegrationSettingsPanelDescriptor } from './integrationPanelTypes';

export const integrationPanelFallbackModules: Record<string, Record<string, unknown>> = {
  './telegram.panel.tsx': srcFeaturesSettingsSectionsIntegrationsTelegramPanelModule
};
