// This file is generated by scripts/generate-generation-param-registry.mjs.
// Keep logical parameter definitions in src/entities/generation-params/fields/**/param.ts.
import { backgroundParam } from './fields/background/param';
import { includeModelParam } from './fields/include-model/param';
import { inputFidelityParam } from './fields/input-fidelity/param';
import { moderationParam } from './fields/moderation/param';
import { nParam } from './fields/n/param';
import { outputCompressionParam } from './fields/output-compression/param';
import { outputFormatParam } from './fields/output-format/param';
import { partialImagesParam } from './fields/partial-images/param';
import { qualityParam } from './fields/quality/param';
import { rawJsonParam } from './fields/raw-json/param';
import { responseFormatParam } from './fields/response-format/param';
import { retryPolicyParam } from './fields/retry-policy/param';
import { sizeParam } from './fields/size/param';
import { streamParam } from './fields/stream/param';
import { styleParam } from './fields/style/param';
import { userParam } from './fields/user/param';
import type { GenerationParamDefinition } from './types';

export const logicalGenerationParamGeneratedModules: Record<string, Record<string, GenerationParamDefinition>> = {
  './fields/background/param.ts': { backgroundParam },
  './fields/include-model/param.ts': { includeModelParam },
  './fields/input-fidelity/param.ts': { inputFidelityParam },
  './fields/moderation/param.ts': { moderationParam },
  './fields/n/param.ts': { nParam },
  './fields/output-compression/param.ts': { outputCompressionParam },
  './fields/output-format/param.ts': { outputFormatParam },
  './fields/partial-images/param.ts': { partialImagesParam },
  './fields/quality/param.ts': { qualityParam },
  './fields/raw-json/param.ts': { rawJsonParam },
  './fields/response-format/param.ts': { responseFormatParam },
  './fields/retry-policy/param.ts': { retryPolicyParam },
  './fields/size/param.ts': { sizeParam },
  './fields/stream/param.ts': { streamParam },
  './fields/style/param.ts': { styleParam },
  './fields/user/param.ts': { userParam }
};
