// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcProvidersComfyuiGenerationRequestSurfaceModule from '../../providers/comfyui/generationRequestSurface';
import * as srcProvidersOpenaiCompatibleGenerationRequestSurfaceModule from '../../providers/openai-compatible/generationRequestSurface';
import type { ProviderGenerationRequestSurface } from './requestSurfaceTypes';

export const providerGenerationRequestSurfaceFallbackModules: Record<string, Record<string, unknown>> = {
  '../../providers/comfyui/generationRequestSurface.ts': srcProvidersComfyuiGenerationRequestSurfaceModule,
  '../../providers/openai-compatible/generationRequestSurface.ts': srcProvidersOpenaiCompatibleGenerationRequestSurfaceModule
};
