// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcProvidersComfyuiGenerationSurfaceModule from '../../providers/comfyui/generationSurface';
import * as srcProvidersOpenaiCompatibleGenerationSurfaceModule from '../../providers/openai-compatible/generationSurface';
import type { ProviderGenerationSurface } from './surfaceTypes';

export const providerGenerationSurfaceFallbackModules: Record<string, Record<string, unknown>> = {
  '../../providers/comfyui/generationSurface.ts': srcProvidersComfyuiGenerationSurfaceModule,
  '../../providers/openai-compatible/generationSurface.ts': srcProvidersOpenaiCompatibleGenerationSurfaceModule
};
