// This file is generated by scripts/generate-extension-registries.mjs.
// Add/remove descriptor modules; do not edit this fallback registry by hand.
import * as srcEntitiesGenerationParamsTabsFrameTabModule from './tabs/frame.tab';
import * as srcEntitiesGenerationParamsTabsOutputTabModule from './tabs/output.tab';
import * as srcEntitiesGenerationParamsTabsRenderTabModule from './tabs/render.tab';
import * as srcEntitiesGenerationParamsTabsRetryTabModule from './tabs/retry.tab';
import * as srcEntitiesGenerationParamsTabsServiceTabModule from './tabs/service.tab';
import type { GenerationParamTabDefinition } from './types';

export const generationParamTabFallbackModules: Record<string, Record<string, unknown>> = {
  './tabs/frame.tab.ts': srcEntitiesGenerationParamsTabsFrameTabModule,
  './tabs/output.tab.ts': srcEntitiesGenerationParamsTabsOutputTabModule,
  './tabs/render.tab.ts': srcEntitiesGenerationParamsTabsRenderTabModule,
  './tabs/retry.tab.ts': srcEntitiesGenerationParamsTabsRetryTabModule,
  './tabs/service.tab.ts': srcEntitiesGenerationParamsTabsServiceTabModule
};
